### ISSUE TITLE
v 0.23.1: module cfnlint.core has no attribute CfnLintExitException

### ISSUE THREAD

**Issue by andrew-glenn** [aws-cloudformation/cfn-python-lint#1090]
Steps to reproduce:

```
pip install cfn-lint
cfn-lint --help
```

CFNLint version:

```
 ~  pip search cfn-lint | head -n 2
cfn-lint (0.23.1)                                        - checks cloudformation for practices and behaviour         that could potentially be improved
  INSTALLED: 0.23.1 (latest)
```

```
 ~  cfn-lint --help
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/cfnlint/__main__.py", line 28, in main
    (args, filenames, formatter) = cfnlint.core.get_args_filenames(sys.argv[1:])
AttributeError: module 'cfnlint.core' has no attribute 'get_args_filenames'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/cfn-lint", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/cfnlint/__main__.py", line 46, in main
    except cfnlint.core.CfnLintExitException as e:
AttributeError: module 'cfnlint.core' has no attribute 'CfnLintExitException'
```

Python version: `Python 3.7.4`

**Comment by andrew-glenn** [comment]
This is also reproducible in a virtenv.

**Comment by andrew-glenn** [comment]
After :coffee: :coffee: and digging further, I had residual package artifacts floating around. Closing.

**Comment by domino14** [comment]
what does this mean? what residual artifacts and how did you remove them.

**Comment by andrew-glenn** [comment]
@domino14 I installed the wrong python package.

**Comment by pjuarezd** [comment]
uninstalling the cfnlint package worked for me
`pip uninstall cfnlint`
