### ISSUE TITLE
[Windows] --update-specs is broken and some tests don't pass

### ISSUE THREAD

**Issue by miparnisari** [aws-cloudformation/cfn-python-lint#1370]
*cfn-lint version* : 0.28.1

*Description of issue.*

On a clean Windows 10 VM:

```bash
C:\Users\User\Desktop\cfn-python-lint>cfn-lint -u
Traceback (most recent call last):
  File "C:\Python38\Scripts\cfn-lint-script.py", line 11, in <module>
    load_entry_point('cfn-lint', 'console_scripts', 'cfn-lint')()
  File "c:\users\user\desktop\cfn-python-lint\src\cfnlint\__main__.py", line 16, in main
    (args, filenames, formatter) = cfnlint.core.get_args_filenames(sys.argv[1:])
  File "c:\users\user\desktop\cfn-python-lint\src\cfnlint\core.py", line 113, in get_args_filenames
    cfnlint.maintenance.update_resource_specs()
  File "c:\users\user\desktop\cfn-python-lint\src\cfnlint\maintenance.py", line 57, in update_resource_specs
    spec = patch_spec(spec, 'all')
  File "c:\users\user\desktop\cfn-python-lint\src\cfnlint\maintenance.py", line 162, in patch_spec
    all_patches = jsonpatch.JsonPatch(cfnlint.helpers.load_resource(
  File "c:\users\user\desktop\cfn-python-lint\src\cfnlint\helpers.py", line 187, in load_resource
    return json.loads(pkg_resources.read_text(package, filename, encoding='utf-8'))
  File "c:\python38\lib\importlib\resources.py", line 168, in read_text
    package = _get_package(package)
  File "c:\python38\lib\importlib\resources.py", line 47, in _get_package
    module = import_module(package)
  File "c:\python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'cfnlint.data.ExtendedSpecs.all\\03_value_types'

C:\Users\User\Desktop\cfn-python-lint>
```

I was also able to reproduce on my personal Windows machine.

The tests don't fully pass either:

```bash
py36 run-test: commands[1] | coverage run -m unittest discover -s test
.............................................................F........................2020-02-18 20:50:55,921 - cfnlint.decode - ERROR - Template 
file not found: test/fixtures/templates/good/core/not_found.yaml
.........................E...........................................................................................................................................................................................................................................................................................................................................................
======================================================================   
ERROR: test_success_rds_dbcluster (unit.module.maintenance.test_patch_spec.TestPatchJson)
Success test
----------------------------------------------------------------------   
Traceback (most recent call last):
  File "C:\Users\mparn\Documents\GitHub\cfn-python-lint\test\unit\module\maintenance\test_patch_spec.py", line 27, in test_success_rds_dbcluster  
    patched = patch_spec(self.spec, 'all')
  File "c:\users\mparn\documents\github\cfn-python-lint\src\cfnlint\maintenance.py", line 163, in patch_spec
    'cfnlint.data.ExtendedSpecs.{}'.format(module), file_path))
  File "c:\users\mparn\documents\github\cfn-python-lint\src\cfnlint\helpers.py", line 187, in load_resource
    return json.loads(pkg_resources.read_text(package, filename, encoding='utf-8'))
  File "c:\users\mparn\documents\github\cfn-python-lint\.tox\py36\lib\site-packages\importlib_resources\_py3.py", line 157, in read_text
    package = _get_package(package)
  File "c:\users\mparn\documents\github\cfn-python-lint\.tox\py36\lib\site-packages\importlib_resources\_py3.py", line 38, in _get_package        
    module = import_module(package)
  File "c:\python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load      
  File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'cfnlint.data.ExtendedSpecs.all\\03_value_types'

======================================================================   
FAIL: test_config_expand_paths (unit.module.config.test_config_mixin.TestConfigMixIn)
Test precedence in
----------------------------------------------------------------------   
Traceback (most recent call last):
  File "c:\users\mparn\documents\github\cfn-python-lint\.tox\py36\lib\site-packages\mock\mock.py", line 1369, in patched
    return func(*newargs, **newkeywargs)
  File "C:\Users\mparn\Documents\GitHub\cfn-python-lint\test\unit\module\config\test_config_mixin.py", line 100, in test_config_expand_paths      
    'test/fixtures/templates/public/rds-cluster.yaml'])
AssertionError: Lists differ: ['tes[22 chars]ublic\\lambda-poller.yaml', 
'test/fixtures/tem[28 chars]aml'] != ['tes[22 chars]ublic/lambda-poller.yaml', 'test/fixtures/temp[26 chars]aml']

First differing element 0:
'test/fixtures/templates/public\\lambda-poller.yaml'
'test/fixtures/templates/public/lambda-poller.yaml'

- ['test/fixtures/templates/public\\lambda-poller.yaml',
?                                 ^^

+ ['test/fixtures/templates/public/lambda-poller.yaml',
?                                 ^

-  'test/fixtures/templates/public\\rds-cluster.yaml']
?                                 ^^

+  'test/fixtures/templates/public/rds-cluster.yaml']
?                                 ^


----------------------------------------------------------------------   
Ran 459 tests in 203.958s

FAILED (failures=1, errors=1)
Couldn't use data file 'C:\\Users\\mparn\\Documents\\GitHub\\cfn-python-lint\\.coverage.py36': Safety level may not be changed inside a transaction
ERROR: InvocationError for command 'C:\Users\mparn\Documents\GitHub\cfn-python-lint\.tox\py36\Scripts\coverage.EXE' run -m unittest discover -s test (exited with code 1)
_______________________________ summary ________________________________ 
ERROR:   py36: commands failed
```

I can fix the first error by changing this line https://github.com/aws-cloudformation/cfn-python-lint/blob/master/src/cfnlint/maintenance.py#L160

to 

```python
module = dirpath.replace('%s' % append_dir, '%s' % region).replace(os.path.sep, '.')
```

but i'm not sure how to fix the second one yet.

**Comment by miparnisari** [comment]
I can't reproduce anymore, closing :)
