### ISSUE TITLE
cfn-lint 0.29.0 installed via homebrew unable to find networkx distribution. 

### ISSUE THREAD

**Issue by harveymonster** [aws-cloudformation/cfn-python-lint#1434]
*cfn-lint version: (`cfn-lint --version`)*
0.29.0 (via Homebrew)

*Description of issue.*
After updating cfn-lint via homebrew, I now get the following error, even when trying to run the command to get the version (`cfn-lint --version`).

```
Traceback (most recent call last):
  File "/usr/local/bin/cfn-lint", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/Cellar/cfn-lint/0.29.0/libexec/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3255, in <module>
    def _initialize_master_working_set():
  File "/usr/local/Cellar/cfn-lint/0.29.0/libexec/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3238, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/Cellar/cfn-lint/0.29.0/libexec/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3267, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/Cellar/cfn-lint/0.29.0/libexec/lib/python3.8/site-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/local/Cellar/cfn-lint/0.29.0/libexec/lib/python3.8/site-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/Cellar/cfn-lint/0.29.0/libexec/lib/python3.8/site-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'networkx~=2.4' distribution was not found and is required by cfn-lint
```

**Comment by chenrui333** [comment]
Taking a look on this now. Thanks for the report.

**Comment by chenrui333** [comment]
Submitted a patch PR, waiting for the CI to merge it.

**Comment by chenrui333** [comment]
Just released the fix, let me know if it works on your end now.

cc @rzyns

**Comment by harveymonster** [comment]
I updated via brew, and all seems to be working. Thanks for the quick fix, @chenrui333.

**Comment by chenrui333** [comment]
np!!
