### ISSUE TITLE
cfn-lint fails using Python 3.9

### ISSUE THREAD

**Issue by mikeabackhouse** [aws-cloudformation/cfn-python-lint#1520]
cfn-lint --version fails running  Python 3.9

```
PS C:\WINDOWS\system32> cfn-lint --version
Traceback (most recent call last):
  File "c:\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python39\Scripts\cfn-lint.exe\__main__.py", line 5, in <module>
  File "c:\python39\lib\site-packages\cfnlint\__init__.py", line 18, in <module>
    from cfnlint.transform import Transform
  File "c:\python39\lib\site-packages\cfnlint\transform.py", line 10, in <module>
    from samtranslator.translator.translator import Translator
  File "c:\python39\lib\site-packages\samtranslator\translator\translator.py", line 2, in <module>
    from samtranslator.model import ResourceTypeResolver, sam_resources
  File "c:\python39\lib\site-packages\samtranslator\model\sam_resources.py", line 5, in <module>
    import samtranslator.model.eventsources.pull
  File "c:\python39\lib\site-packages\samtranslator\model\eventsources\pull.py", line 5, in <module>
    from samtranslator.translator.arn_generator import ArnGenerator
  File "c:\python39\lib\site-packages\samtranslator\translator\arn_generator.py", line 1, in <module>
    import boto3
  File "c:\python39\lib\site-packages\boto3\__init__.py", line 16, in <module>
    from boto3.session import Session
  File "c:\python39\lib\site-packages\boto3\session.py", line 17, in <module>
    import botocore.session
  File "c:\python39\lib\site-packages\botocore\session.py", line 28, in <module>
    import botocore.configloader
  File "c:\python39\lib\site-packages\botocore\configloader.py", line 19, in <module>
    from botocore.compat import six
  File "c:\python39\lib\site-packages\botocore\compat.py", line 150, in <module>
    import xml.etree.cElementTree
ModuleNotFoundError: No module named 'xml.etree.cElementTree'
```

Issue is relates to / caused by: Boto package
https://github.com/boto/botocore/issues/2002

**Comment by kddejong** [comment]
Python 3.9 was released so this is moving to the top of the list.

**Comment by PatMyron** [comment]
@mikeabackhouse is this issue still outstanding? I see the `botocore` issue has been resolved
