### ISSUE TITLE
Linter not working and always crashing in my VS Code after it is being installed

### ISSUE THREAD

**Issue by vinod827** [aws-cloudformation/cfn-python-lint#1709]
*cfn-lint version: (`cfn-lint --version`)*
v0.14.1

VS Code version -> 1.49.1
***Description of issue.***
CloudFormation Linter is crashing every time I open the VS Code.

**Crash log**
```
Settings have been updated...
Settings: {"cfnLint":{"enableAutocomplete":true,"validateUsingJsonSchema":false,"path":"cfn-lint","appendRules":[],"ignoreRules":[],"overrideSpecPath":""}}
Determined this file is a CloudFormation Template. file:///Users/apple/my-project/template.yaml. Found the string AWSTemplateFormatVersion
Running... cfn-lint --format,json,--,"/Users/apple/my-project/template.yaml"
/bin/sh: cfn-lint: command not found

child process exited with code 127 and signal null
undefined:1



SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at ChildProcess.<anonymous> (/Users/apple/.vscode/extensions/kddejong.vscode-cfn-lint-0.14.1/server/out/server.js:198:28)
    at ChildProcess.emit (events.js:223:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
[Info  - 11:53:00 AM] Connection to server got closed. Server will restart.
Settings have been updated...
Settings: {"cfnLint":{"enableAutocomplete":true,"validateUsingJsonSchema":false,"path":"cfn-lint","appendRules":[],"ignoreRules":[],"overrideSpecPath":""}}
Determined this file is a CloudFormation Template. file:///Users/apple/my-project/template.yaml. Found the string AWSTemplateFormatVersion
Running... cfn-lint --format,json,--,"/Users/apple/my-project/template.yaml"
/bin/sh: cfn-lint: command not found

child process exited with code 127 and signal null
undefined:1
```

**Comment by PatMyron** [comment]
[`cfn-lint` is not yet bundled with the Visual Studio Code extension](https://github.com/aws-cloudformation/aws-cfn-lint-visual-studio-code/issues/60) and must be installed separately:
`pip3 install cfn-lint --upgrade`
(make sure it's installed in your [`$PATH`](https://en.wikipedia.org/wiki/PATH_(variable)) if you're still having issues after installing)
