### ISSUE TITLE
DeprecationWarning with setuptools 40.8.0

### ISSUE THREAD

**Issue by yan12125** [aws-cloudformation/cfn-python-lint#691]
*cfn-lint version: (`cfn-lint --version`)*: 0.15.0

*Description of issue.*
```
$ PYTHONWARNINGS=error:Use cfn-lint --version
Traceback (most recent call last):
  File "/usr/bin/cfn-lint", line 11, in <module>
    load_entry_point('cfn-lint==0.15.0', 'console_scripts', 'cfn-lint')()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.7/site-packages/cfnlint/__init__.py", line 26, in <module>
    import cfnlint.helpers
  File "/usr/lib/python3.7/site-packages/cfnlint/helpers.py", line 211, in <module>
    initialize_specs()
  File "/usr/lib/python3.7/site-packages/cfnlint/helpers.py", line 208, in initialize_specs
    RESOURCE_SPECS[reg] = load_resources(filename=('/data/CloudSpecs/%s.json' % reg))
  File "/usr/lib/python3.7/site-packages/cfnlint/helpers.py", line 129, in load_resources
    filename
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1145, in resource_filename
    self, resource_name
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1395, in get_resource_filename
    return self._fn(self.module_path, resource_name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1471, in _fn
    self._validate_resource_path(resource_name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1535, in _validate_resource_path
    stacklevel=4,
DeprecationWarning: Use of .. or absolute path in a resource path is not allowed and will raise exceptions in a future release.
```

**Comment by yan12125** [comment]
Hi @kddejong thanks for looking into this issue! I applied patch #693, but the deprecation warning is still there:
```
$ PYTHONWARNINGS=error:Use cfn-lint --version
Traceback (most recent call last):
  File "/home/yen/.local/bin/cfn-lint", line 11, in <module>
    load_entry_point('cfn-lint==0.15.0', 'console_scripts', 'cfn-lint')()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/yen/.local/lib/python3.7/site-packages/cfnlint/__init__.py", line 26, in <module>
    import cfnlint.helpers
  File "/home/yen/.local/lib/python3.7/site-packages/cfnlint/helpers.py", line 205, in <module>
    initialize_specs()
  File "/home/yen/.local/lib/python3.7/site-packages/cfnlint/helpers.py", line 202, in initialize_specs
    RESOURCE_SPECS[reg] = load_resources(filename=('/data/CloudSpecs/%s.json' % reg))
  File "/home/yen/.local/lib/python3.7/site-packages/cfnlint/helpers.py", line 127, in load_resources
    return json.loads(pkg_resources.resource_string(__name__, filename))
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1157, in resource_string
    self, resource_name
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1401, in get_resource_string
    return self._get(self._fn(self.module_path, resource_name))
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1471, in _fn
    self._validate_resource_path(resource_name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1535, in _validate_resource_path
    stacklevel=4,
DeprecationWarning: Use of .. or absolute path in a resource path is not allowed and will raise exceptions in a future release.
```

By the way, if I change this line in `cfnlint/helpers.py`
```
    RESOURCE_SPECS[reg] = load_resources(filename=('/data/CloudSpecs/%s.json' % reg))
```
into:
```
    RESOURCE_SPECS[reg] = load_resources(filename=('data/CloudSpecs/%s.json' % reg))
```
The warning goes away.

**Comment by kddejong** [comment]
Huh, I tried that and it didn't work for me.  I will try it again.

**Comment by kddejong** [comment]
You're correct.  I was able to remove the warnings by remove the leading `/`.  I have updated the pull request.

**Comment by yan12125** [comment]
Thank you for the PR! I can confirm there are no longer warnings in cfn-lint with the latest git commit.
